# permissions for end users to edit prometheusruletuners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: get-resources
    app.kubernetes.io/managed-by: kustomize
  name: prometheusruletuner-editor-role
rules:
- apiGroups:
  - sre.taikun.cloud
  resources:
  - prometheusruletuners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sre.taikun.cloud
  resources:
  - prometheusruletuners/status
  verbs:
  - get
