---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sre.taikun.cloud
  resources:
  - resourcestuner
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sre.taikun.cloud
  resources:
  - resourcestuner/finalizers
  verbs:
  - update
- apiGroups:
  - sre.taikun.cloud
  resources:
  - resourcestuner/status
  verbs:
  - get
  - patch
  - update
