name: Build and Push Operator Image & Helm Chart

on:
  push:
    branches: ["main"]
    paths:
      - "operators/get-resources/**"
      - "helm-charts/**"
      - ".github/workflows/operator-ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: get-resources

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tidy Go Modules
        run: |
          cd operators/get-resources
          go mod tidy

      - name: Build and Push Docker image
        run: |
          cd operators/get-resources
          make docker-build IMG=docker.io/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest
          make docker-push IMG=docker.io/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest

  helm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Lint Helm Chart
        run: helm lint ./helm-charts/get-resources

      - name: Template Helm Chart
        run: helm template get-resources ./helm-charts/get-resources

      - name: Package Helm Chart
        run: |
          mkdir -p ./helm-charts/pkg
          helm package ./helm-charts/get-resources --destination ./helm-charts/pkg

      - name: Upload Chart Artifact
        uses: actions/upload-artifact@v4
        with:
          name: get-resources-chart
          path: ./helm-charts/pkg/get-resources-*.tgz


