name: Build and Push Operator Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "operators/prometheus-tuner/**"
      - ".github/workflows/operator-ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: prometheus-tuner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          cd operators/prometheus-tuner
          make docker-build IMG=docker.io/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest
          make docker-push IMG=docker.io/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest
